### ISSUE TITLE
Directory background support

### ISSUE THREAD

**Issue by rixtox** [oleg-shilo/shell-x#10]
Currently the `[folder]` target only works on right clicking folder icons. However it would be more useful if it also works on explorer's directory background. It would allow implementing menus similar to "Open in Windows Terminal" become possible.

**Comment by Venipa** [comment]
second this

**Comment by oleg-shilo** [comment]
I am not sure that the right-click event of this sort is propagated by shell extensions. But will check. If it does then it is an easy enhancement to implement.

**Comment by oleg-shilo** [comment]
Done.
The feature will be available in the very next release.

**Comment by oleg-shilo** [comment]
Done. 
https://github.com/oleg-shilo/shell-x/releases/tag/v1.3.0.0
It will also be available from Choco as soon as the moderation review is finished
