### ISSUE TITLE
Import current contexts from registry?

### ISSUE THREAD

**Issue by jeremymeyers** [oleg-shilo/shell-x#11]
Would it be possible to pull in the existing context menu settings from the registry so changes can be made rather than having to recreate? 

Maybe even including a batch file with the distro that can export the keys in question for parsing (so the program doesn't touch the registry directly)

**Comment by oleg-shilo** [comment]
Not sure I follow. 
The application is designed to inject user-defined items into the existing context menu by avoiding touching the registry.
Can you elaborate on your proposal?

**Comment by jeremymeyers** [comment]
Oh I see.  I was thinking of it in terms of being able to edit and rebuild the entirety of the context menu per extension.

**Comment by oleg-shilo** [comment]
Theoretically, it is possible. 
One can write a script that reads the registry, creates the sell-x equivalent and then deletes the registry.

But... this in turn creates such a mess with the UX and completely messes up with the whole concept of the file system item right-click interaction. Potentially impacting the other products that can depend on the registry entries associated with the file extension.

Even facing the question "what should happen when you uninstall shell-x" would make you shiver :)
