### ISSUE TITLE
[Request] Special folder just for files

### ISSUE THREAD

**Issue by ActualMandM** [oleg-shilo/shell-x#13]
Similarly to #3, this would be a special folder like `[any]` and `[folder]` but would only appear for files.

**Comment by oleg-shilo** [comment]
But `[any]` is exactly the one for all files:
![image](https://user-images.githubusercontent.com/16729806/189311480-6b57220d-7212-4560-b7f3-5cf631cafd97.png)

Did you mean something else?

**Comment by ActualMandM** [comment]
`[any]` applies to both files and folders.

**Comment by oleg-shilo** [comment]
OK, I see your point.
Will schedule the implementation for the next release (in 1-2 weeks).

**Comment by oleg-shilo** [comment]
Done.

I have also created an option for testing the configuration outside of Windows explorer.

```
shell-x -test [path]
```
It is helpful for refining the mapping of the configuration to the selected item (path) actions without attaching to the explorer process.

![image](https://user-images.githubusercontent.com/16729806/191431089-d71bbc08-1722-4cae-ae2d-b315129902eb.png)

I am going to release and publish a new version as soon as you can test the changes and you are happy with the result.

**Comment by ActualMandM** [comment]
Just tried it out, seems to be working great!

**Comment by oleg-shilo** [comment]
Txs. 
Published on Choco now.
