### ISSUE TITLE
Question about executing the BAT file in the menu

### ISSUE THREAD

**Issue by Ahernz** [oleg-shilo/shell-x#16]
Could you add a parameter to enable the selected files to execute the BAT file in the menu separately?

**Comment by oleg-shilo** [comment]
Can you elaborate?
What exactly do you mean "selected files to execute the batch file"?

**Comment by Ahernz** [comment]
Sorry, I can't speak English, this is the software translation, there may be a mistake in expression.
Let's say I have a "I can put the extension. Change MP4 to.m4v "BAT file.
I can't apply it to the file of my choice,
Can only be used to select the first file,
I wonder if you can understand this explanation?
Thank you for 《Shell-X》, it helped me a lot.

**Comment by oleg-shilo** [comment]
Actually, you can achieve it.

select the file. have its extension (.mp4) mapped to the renaming script (e.g. `rename MP4.cmd`). You are done.
You can also do it on multiselection.
You can also have it as a folder action `rename all MP4.ps1`

**Comment by Ahernz** [comment]
It's like this  rename MP4.bat

>@echo off
>ren "%~dp1%~n1.mp4" "%~n1.m4v"
>pause

I do this when I have multiple selections,
It only works when I select the first file.

I don't want to rename all the files MP4,
I just need to rename the MP4 file I selected.

**Comment by oleg-shilo** [comment]
in your batch file, all selected files are passed to you. Though you are only accessing the first one with `%1`. 

To access all arguments you need to use `%*`.

Though if I was you I would not bother with a batch file. It's too restrictive. I would use any sort of scripting: ps1, cs-script, python,.... 

![image](https://user-images.githubusercontent.com/16729806/192128510-865eec28-5cd4-4e97-a047-0dccd1f716bb.png)

![image](https://user-images.githubusercontent.com/16729806/192128518-d4d69af7-b093-4de0-a407-e4f17d525c2d.png)

And now selecting two XML files produces this:
![image](https://user-images.githubusercontent.com/16729806/192128531-231ce42e-ef19-481f-b04a-29ab1695d892.png)

![image](https://user-images.githubusercontent.com/16729806/192128567-a6996edc-b710-45d6-9575-ff3dbc688959.png)

**Comment by Ahernz** [comment]
I'm sorry, because I'm not a programmer, so I can't program.
But I have an idea,
Run bat for each file separately.
This is also the default way for Windows,
Add the "% 1" parameter to the registry.
Because I prefer to use shell-x,
So I just want to ask if you can add such a mode.
![1 (1)](https://user-images.githubusercontent.com/76786517/192142629-67fa7de7-47c5-46ab-916c-b9a8996c8167.gif)
![1 (1)](https://user-images.githubusercontent.com/76786517/192142613-f70347f3-38e9-49fd-b659-f73d7b6a2f69.png)
![1 (2)](https://user-images.githubusercontent.com/76786517/192142619-8a760ea6-bc28-4a81-b34f-4f25a374e366.png)
![1 (3)](https://user-images.githubusercontent.com/76786517/192142621-99f8cfd8-e775-4661-ab1c-f9c76d35b308.png)

**Comment by oleg-shilo** [comment]
Actually, it is not a  default mode of explorer. You simply decided to encode it as %1 and the explorer accommodates it.
In fact, passing %* is preferable as in this case handling app (e.g. batch file) can decide to handle the selected items one by one or as a set. If you decide to go with %1 as default, the handling app cannot possibly implement the selection set scenario. That's why %* approach is default.

I made it to the 'envhancement'

**Comment by oleg-shilo** [comment]
Done, will publish soon.

**Comment by Ahernz** [comment]
Thanks, because I have many uses.
Because I usually use bat more,
For example, I can label folders or prefix file names.
It's great to have your help.

**Comment by Ahernz** [comment]
I found a bug. After adding. ms to the file name, the path with spaces is not completely displayed.

**Comment by oleg-shilo** [comment]
> have already donated
Thank you mate for your support. Greatly appreciated.

Interestingly enough there was some problem with preparing the display text for menu items but of a different nature. I have just fixed it. 

I also made the release v1.5.0 and published it on Choco though it will take some time before the choco moderation is done.

If you still experience the problem with the latest release then send me the exact file name (path) example that triggers the problem and I will just make the fix and the release right away.

**Comment by Ahernz** [comment]
I downloaded the v1.5.0 version, but this version seems incorrect.

**Comment by oleg-shilo** [comment]
Indeed there was something wrong with the packaging. Please try again. The version of the included file is correct. But I am interested if it addressed the issue you were facing earlier.

**Comment by Ahernz** [comment]
It's solved, very good.

**Comment by oleg-shilo** [comment]
Updating choco then.
