### ISSUE TITLE
When multiple files are selected, the shell-x menu is not displayed.

### ISSUE THREAD

**Issue by Ahernz** [oleg-shilo/shell-x#18]
When the root folder is [any], select multiple files to display the Shell-x menu,
When the root folder is [file], the Shelll-x menu cannot be displayed when multiple files are selected,

**Comment by oleg-shilo** [comment]
Can you please elaborate?
I am not sure what are the steps to reproduce the problem.

**Comment by Ahernz** [comment]
When batch files are placed in the root folder [any].
![2022-10-14_14-15-37](https://user-images.githubusercontent.com/76786517/195775932-8b2ba709-f907-4fad-b5b2-a7d7127b7e11.png)
If I select a file, the right-click menu can display shell-x.
![动画1](https://user-images.githubusercontent.com/76786517/195776151-f9203590-68f3-4b46-8114-5c34a1b1cef0.gif)
If I select multiple files, the right-click menu cannot display shell-x.
![动画2](https://user-images.githubusercontent.com/76786517/195776410-d6482d8f-47fd-47d3-9809-2b0a6ba32c92.gif)
If I put the batch file in the root folder [any], this problem will not occur.

**Comment by oleg-shilo** [comment]
Sorry, I just repeated the test you are trying to do and it seems to work:
![image](https://user-images.githubusercontent.com/16729806/195989104-f93e234f-e018-4dc2-844c-e51622eb2884.png)

Is it possible that the failure is triggered for non inglish files only? Can you check that you still have the same problem if you batch file hs only English characters in the file name?

**Comment by Ahernz** [comment]
I'm sorry, that's my reason. This happened because I deleted the {any} folder.
