### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by hunterfrerich** [oleg-shilo/shell-x#19]
When installed manually, I can't delete the original `shell-x.exe` or `SharpShell.dll`.  It is "in use".
  
There is no documentation on this, and this program is not visible in Windows "Apps and Features", startup, autoruns, or services.  
  
How do I uninstall?

**Comment by oleg-shilo** [comment]
You cannot see any Shell Extensions in "Apps and Features" as it is not an app but an extension to the Windows Explorer app.
Windows explorer may prevent removing any she'll extension if it has it running (loaded).

In such cases, the solution is to restart the explorer. I mean truly restart not close and open the explorer window. And then deregister the extension. If you use Chocolatey to install this extension then it does it for you automatically

I have updated the home page with the instructions:

  >To uninstall just execute:
     ```
     shell-x -unregister
     ```
     Note, the explorer may lock the extension file so yuo may need to restart it before you can the file.
