### ISSUE TITLE
Unnecessary double quotation marks

### ISSUE THREAD

**Issue by yzhang-gh** [oleg-shilo/shell-x#2]
(This program is AWESOME! Thanks a lot)

One minor bug

> The content of 00.Notepad.cmd file is an ordinary batch file content:
>
> ```
> notepad.exe "%*"
> ```
> https://github.com/oleg-shilo/shell-x#how-it-works

It seems that we don't need the double quotation marks, which will cause a problem if the path contains spaces.

**Comment by oleg-shilo** [comment]
Good point. Thank you.
Done: https://github.com/oleg-shilo/shell-x/releases/tag/v1.0.1.0

**Comment by yzhang-gh** [comment]
🍻
