### ISSUE TITLE
[Question - Feature] Auto scroll (or with mouse wheel) the menu

### ISSUE THREAD

**Issue by masterofobzene** [oleg-shilo/shell-x#21]
Is it possible to change the menu scroll behaviour?  right now we have to click the arrows, is there any way to change it so it activates when hovering? or when we use the scroll wheel (ideal).

![2023-01-24 14-53-17](https://user-images.githubusercontent.com/94469116/214370298-6a730b60-1bff-4879-9ef7-a4854d7eafcc.png)

**Comment by oleg-shilo** [comment]
Unfortunately, it's not feasible. 
The operating system implements the menu popup and the application (shell-x) has no control over how it behaves.
