### ISSUE TITLE
Multiple procesing sometimes fail

### ISSUE THREAD

**Issue by masterofobzene** [oleg-shilo/shell-x#27]
Using a TEST.c.ms.cmd with this code *SOMETIMES* crashes when selecting at least 15 files to process.

TEST.c.ms.cmd Code:

```

@echo off

for %%A in (%1) do set MYFILE=%1
SET DEST="W:\SOMEFOLDER\[SOMEFOLDER]"
if not exist %DEST% (goto error) else (XCOPY /V %MYFILE% %DEST%)
if errorlevel 0 (del /Q %MYFILE%) else (goto error)


GOTO EXIT

::ERROR HANDLER
:error
cls
echo ERROR EN PATH DE DESTINO: %DEST% no existe.

::PREGUNTA
SET /P M=Deseas crearlo?:
IF %M%==S GOTO SI
IF %M%==N GOTO NO

:SI
MKDIR %DEST%
echo HECHO. Volve a correr el script para mover el archivo.
timeout 3
exit

:NO
echo NO SE HIZO NADA.
timeout 3
exit

:EXIT
EXIT
```

**Comment by oleg-shilo** [comment]
Sorry, we did not solve it. 

It's really hard to address without reproducing.

ShellExtensions are COM technology and despite being a vital part of OS for decades, it may fail. Another COM-based tech that often fails - clipboard management. With MultiClip I just had to give up and simply accept random failures.
