### ISSUE TITLE
Problems running multiple instances of batch files

### ISSUE THREAD

**Issue by masterofobzene** [oleg-shilo/shell-x#28]
Hello Oleg

Here I am again after so much time with the problem with batch files not working as intended. This time I think I kind of figured out a pattern of failures and the root cause seems to be a race condition or something like that.

Let me explain this with an example because it would be difficult to me otherwise:

We made around 100 entries for the menu using shell-x. Yes a lot. No icons.
These entries are separated into folders: 
`C:\Users\someone\AppData\Roaming\shell-x\[gif,mp4,mov,mpg,mpeg,avi,mkv,webm,ts,wmv,m4v,flv]\02.MOVER A EXTERNO\HIGHLIGHTS\TODO` then inside "TODO" folder, we have even more folders each with a batch file in it, e.x: `.\TODO\A\A.c.ms.cmd` , `.\TODO\B\B.c.ms.cmd`  and so on until Z.

We also have special bat files that we put in a similar structure, say for example:
`C:\Users\someone\AppData\Roaming\shell-x\[gif,mp4,mov,mpg,mpeg,avi,mkv,webm,ts,wmv,m4v,flv]\02.MOVER A EXTERNO\CLIPS\TODO` . The rest is the same than with the above.

Now to the problem:

If you select , let's say 200 files, (could be small videos or pictures but never mixing each) and try to use shell-x to send them to "HIGHLIGHTS" folder using my batch files, the script sends them to "CLIPS" instead.  
I'm going crazy with this as it also seems to crash the batch files sometimes too.  
Same batch with less files works as intended, meaning instead of 200 files we select around 20, it works.
What I've discovered (or think so) is that the "CLIPS\TODO" folder containing all subfolders and cmd files for shell-x is "first" in the order. 

To be more graphic on the structure:
```
[gif,mp4,mov,mpg,mpeg,avi,mkv,webm,ts,wmv,m4v,flv]\02.MOVER A EXTERNO
       |-- CLIPS
       |       |_A
       |         |_ "A.c.ms.cmd"
       |       |_B
       |         |_ "B.c.ms.cmd"
       |
       |-- HIGHLIGHTS
       |       |_A
       |         |_ "01A.c.ms.cmd"
       |       |_B
       |         |_ "02B.c.ms.cmd"
```

It seems that shell-x has some kind of race condition in which it searches for the given cmd file and instead of executing the correct one, it executes the first it finds with a similar name.

For example, given the structure above, if you execute `RIGHT CLICK -> MOVER A EXTERNO -> HIGHLIGHTS -> A -> A.c.ms.cmd`  it will execute `MOVER A EXTERNO -> CLIPS -> A -> 01A.c.ms.cmd` instead because "CLIPS" is above "HIGHLIGHTS" and both cmd files have very similar names.
I did an experiment and changed the name from "HIGHLIGHTS" to "[HIGHLIGHTS]" so the folder goes first in the order, and it worked.
The problem with this approach is that I will be breaking "CLIPS" or other folders too.

I don't comprehend how shell-x works under the hood, but from my ignorance it looks like if it were using a diffuse search and executing the first diffuse result given the ordering of the folders, with diffuse I mean that it checks partially into a registry/table/dbase of some kind and matches the result inconsistently.

**Comment by oleg-shilo** [comment]
Let me reflect on your findings and see what can be done.

**Comment by oleg-shilo** [comment]
A few points that can help you.
- You will probably have a more predictable environment if you have a folder structure named consistently. I am not sure, maybe it's just a typo but in your post, you do not have a dot character separating the batch file index from its display name. It can lead to incorrect titles, wrong order and even incorrect execution context.
- There is no any synchronisation between selected files execution. The concurrency model is no different to double-clicking. every batch file is executed and it finishes when it decides. Thus you may potentially execute another batch of 200 while the previous one is not finished yet.
- using option `ms` (multselect) is not a very good approach as it spawns as many parallel processes as many files selected. It's better to have a script of a sort that receives all your 200 selected files and processes them one by one. Or at least have a thread pool (e.g. execute all files in 20 threads). For that, you will need to drop the `ms` suffix and develop such a script (e.g. C# script, powershell script).
- in my experiment, I can start 16 files with `.ms.` but not 17. It looks like there is some sort of protection against misbehaving executables.

**Comment by oleg-shilo** [comment]
It looks like on my system it does not even invoke the shell extension file handler for 17 files at all.

**Comment by oleg-shilo** [comment]
I have just made the release [v1.5.7](https://github.com/oleg-shilo/shell-x/releases/tag/v1.5.7.0)

- Added option to keep the console open for console commands with non-empty envar SHELLX.KEEPCONSOLE
- Update PowerShell command support. It was needed because PS CLI changes
- Update of SharpShell and ServerRegistrationManager packages.

The 16 selected items limit seems to be a constraint of my environment. There is nothing in this release that would directly address your problem as I cannot reproduce it in my environment. However, there is an update of the SharpShell library that is responsible for the core integration with Explorer. 

I have also updated the PowerShell script handling since PS got the CLI update, and the old API was no longer working.

And here are two examples of how to implement looping through the args (when there is no `.ms.` suffix) in the script.

The example executes (loads) every arg with notepad.exe:

`01.cmd-loop.c.cmd` script
```cmd
for %%x in (%*) do (
   rem start and wait
   rem notepad %%~x 

   rem start and continue
   start notepad %%~x 
)
```   
`02.ps-loop.c.ps1` script
```ps1
# Iterate through each argument and open in Notepad
foreach ($file in $args) {
    Start-Process notepad $file
}
```

**Comment by oleg-shilo** [comment]
Yes, I have tested the cmd example.

**Comment by oleg-shilo** [comment]
>...since simply drag and dropping the files to the batch produces the same effect without shell-x doing anything.

Yes, this is a very good definitive test that proves our early observations. The limit is imposed by the OS but not by the tools.
BTW, in my case, it is 16. Exactly 16. 
I did a quick search yesterday but could not find anything definitive, except ChatGPT's suggestion that this can be an OS security measure, but without any details.

Though the fact that on one system it is 16 and on another 75 suggests that it is something configurable.

**Comment by oleg-shilo** [comment]
BTW:

> Yes, there is a limitation in Windows that restricts the maximum number of files that can be dragged and dropped at one time. This limit is determined by the size of the command-line argument buffer, which is capped at approximately 32,767 characters.

**Comment by oleg-shilo** [comment]
Bingo!

My test folder was inside of a deep nested directory so it is 16. I moved it to the root of the drive and now I can do 50+

**Comment by oleg-shilo** [comment]
exactly.

And now I managed to hit the actual args string length limit with long names and 404 selected files. When it happens there is a nice informative message:
![image](https://github.com/user-attachments/assets/e4405126-2816-4bee-be27-621bde67b7dd)

Meaning that my yesterday 16, yours 75 and 60 are some strange and wonderful things that Win does under the hood.

**Comment by oleg-shilo** [comment]
Sorry mate. It means that you do not have many options except practising some pragmatic limit on select operations.
Well, we learned something today.

Happy new year.

**Comment by oleg-shilo** [comment]
> At this point you probably hate me.

:) Don't stress. No one hates no one.

OK, I got my system to show the problem as yours. Managed to do that only when I started using your file names: `filename [2] - (test).mkv`

This si great as I can work on it now.
Leave it with me I will help you with that.

**Comment by oleg-shilo** [comment]
OK, I am not sure what is happening but PS does indeed plays up. At least in my environment.

These are my findings:

Input:
- two selected files with names: "New folder\filename [2] - (test).mkv.txt" and "New folder\filename [3] - (test).mkv.txt"
- PS script (01.ps-loop.c.ps1):
  ```powershell
    Write-Host "starting."

    # Start-Process notepad 

    # Check if any arguments were passed
    if ($args.Count -eq 0) {
        Write-Host "No file names provided."
        exit
    }

    # Iterate through each argument and open in Notepad
    foreach ($file in $args) {
        # Check if the file exists
        if (Test-Path $file) {
            Write-Host "Opening file: $file"
            Start-Process notepad $file
        } else {
            Write-Host "File not found: $file"
        }
    }

    # Optional: Display a count of successfully processed files
    Write-Host "`nTotal files processed: $($args.Count)"
  ```
  - Environment: envar `SHELLX.KEEPCONSOLE` set to `"yes"` to force PS terminal to stay visible.
  
  This is what I have observed:
  
  1. Everything works OK if I do not have `[...]` in the file name. It shouldn't be this way but it is.
  2. Everything works OK if I only select a single file. Even with `[...]` in the file name.
  3. When two files selected the PS terminal prints this output:
     ![image](https://github.com/user-attachments/assets/a5b5da5c-0e5a-4381-a6d2-a55e3ca3db87)
      This is a PS noncence because both files exist. Otherwise the Explorer would not let select them.
      If I select three files then all will fail but the last one:
      ![image](https://github.com/user-attachments/assets/8def84c5-55c9-4732-a7b5-a31906794242)
   4. When I removed the `Test-Path $file`  condition and open the files without checking everything works just fine:
      ![image](https://github.com/user-attachments/assets/13fb371c-f5a1-4b9c-ba4e-a32d6f254bae)
      
 There is something very dodgy with the PS checking the file existance.
 Thus changing the script file mane to "01.ps-loop.c.ms.ps1" also helps. Simply because in this case for opening N files there will be Nscripts executed. And PS is fine with a single arg passed

**Comment by oleg-shilo** [comment]
As a side note, if you find using PS a bit awkwarcuard, I do not blame you. 

If you are comfortable with the full scale power of C# then I can offer you an alternative. You can use C# scripts instead of PS.

You can add this capability to your environment if you have .NET v7+ SDK installed. Just execute in the terminal:

```cmd
dotnet tool install --global cs-script.cli
``` 

Now you can execute C# scripts.
This is how you can invoke the C# script launcher `css.exe`:
```cmd
css.exe "<path to your C# script folder>\css-loop.cs" %* 
pause
```

And the css-loop.cs is just an ordinary C# file:

```C#
//css_include global-usings
using System.Diagnostics;

foreach (var arg in args)
{
    if (File.Exists(arg))
        Process.Start("notepad.exe", $"\"{arg}\"");
    else
        Console.WriteLine($"File does not exist: {arg}");
}
```

This script does not suffer form the problem we both saw in PS scripts.

You can find everything about CS-SCript here: https://github.com/oleg-shilo/cs-script

**Comment by oleg-shilo** [comment]
OMG. PS is even more screwed than I thought.
We were fighting with the problem on different fronts and I also have a few things to share.

1. The problem I was digging into was about PS failing 'file exist' test. I was initially blaming the CLI arguments not being correctly quoted. The truth is uglier. PS does not like square brackets with some integers inside as it tries to interpret it some way.
I have attached the [simple test](https://github.com/user-attachments/files/18296088/ps.zip):<br>
![image](https://github.com/user-attachments/assets/d3c1bc33-bf28-4946-a89e-a90a618c8dc3)
![image](https://github.com/user-attachments/assets/6afdd644-3de3-4bee-962d-f7c0e162285c)
It explains why avoiding the file-exist test lets us through.
This link confirms that there is some black magic there: 
https://stackoverflow.com/questions/64077293/powershell-script-with-a-path-with-square-brackets-in-a-string-for. <br>
> Anyway... Windows Powershell is fucked up:...

ABSOLUTELY!!! 

2. "PS1 don't run well. As it is now, shell-x is sending filenames without proper quoting."
    I know you are under this impression. You provided evidence that cannot be interpreted in any other way. But I am so puzzled about that. 
In my experiments, the args were always quoted. I specifically investigated this possible cause. When I analysed the code I  saw no path that would lead to the problem. Anyway... I cannot ignore the evidence so I reworked the algorithm and now it does always qupt even if there are no spaces in the args.
    To make things even more manageable, I will release a version with enabled debug output. This way the users can always see what was the shell execution command. Thus the command can be copied from the global Dbg trace listener and executed in the terminal when troubleshooting is needed:
   
    ![image](https://github.com/user-attachments/assets/5f980206-dce1-42b7-b07b-c79c7f8cb173)
    
    This way it's false easy to see if the args are quoted or not.

3. "2- There is a limit to selected files for processing, probably Windows thinking we are stupid and not letting us do stuff. "
    That is an excellent finding. It explains a lot. I will include the reference to this behaviour in the readme.
    
    
Stay tuned. I will do the release today.

**Comment by oleg-shilo** [comment]
Done. You can update to the Release v1.5.9.0

**Comment by oleg-shilo** [comment]
Did the Release v1.5.9.0 work for you?

**Comment by oleg-shilo** [comment]
Great. 
And I checked the SimpleContextMenus repo. It uses the same approach as shell-x. In fact I am not sure if this project was not triggered by shell-x. Too many resemblances.
It's OK if indeed it is the case. That's the meaning of Open Source :)

As for Powershell, I completely share your opinion on that. I am shocked to lear how buggy it is. I was under the impression that it has an awkward syntax but an OK implementation. I was so wrong...
