### ISSUE TITLE
Add support for folder

### ISSUE THREAD

**Issue by DenisBalan** [oleg-shilo/shell-x#3]
Add folder support to be able to use shell integration not only for files

**Comment by oleg-shilo** [comment]
Makes sense. Agree.
Marked as an enhancement.

**Comment by oleg-shilo** [comment]
Done in v1.1.0.0

**Comment by oleg-shilo** [comment]
Though it will take some time to appear in choco.

If you don't want to wait then you can take it from the the releases page.

The new convention is `[folder]` directory.

**Comment by aminya** [comment]
It would be good to document the "Done" issues in the readme and close them!
