### ISSUE TITLE
Register for all the Users

### ISSUE THREAD

**Issue by tanonl** [oleg-shilo/shell-x#7]
Hi, I love what you did. It is really useful for me.

I wonder if it is possible to register the context menu so it appears on all the Users sessions ?

**Comment by oleg-shilo** [comment]
Thanks.

I deliberately limited the configured menu items to the current user for privacy protection reasons. 
But... if COM registers the shell extension for _all users_ then it can be done bu moving the  configuration to the _all users_ profile.

Can you check for me if the root level shell-x menu item in he context menu exist for other users?

**Comment by oleg-shilo** [comment]
No answer....
